* <2015-11-5>
** Plans for Work Night
*** Work with ROPS (Serial Communication to and from HKN Robot)
*** Start Developing Psuedo-Code
* <2015-10-30>
** Set Up ROS on One of Murray's Laptops
** Procured the HKN Robot (GUTTED IT!!!) 
*** Will be used for future testing of code
* <2015-10-29>
** Selected Primary Onboard Computer
	 We will probably be using the [[https://developer.nvidia.com/jetson-tk1][Nividia Jetson TK1]]
	 We will probably still accept the XES Board to Experiment and Learn With.
** Discussed Using ROS for Software Framework
	 [[http://www.ros.org/about-ros/][About ROS]]
** Deliberation Meeting
	 The deliberation meeting went very well
	 The budget for next year is approximately $6400
* <2015-10-23>
** Worked On Contingency Form
*** Added Cameras 
*** Added Microcomputers
*** Added Misc
** Safety Training
   Karl (from SAE) conducted safety training for those who had not yet completed it
* <2015-10-15>
** General Meeting Highlights
*** Main [[http://www.pioneerrobotics.weebly.com][Website]] started.
*** Looked at [[http://www.e-consystems.com][camera]].
*** General overview of the contingency request form.
    We are still looking and thinking of items that we want to add to the contingency form.
    We want as much money and as many items on it as possible, since we will only get a fraction of the money that we ask for.
** Software Meeting Highlights
*** The board from XES will probably consumes too much power
    Marshall explained that the board we were looking at from XES will probably not be ideal for our use because it consumes too much power.
    Marshall also explained that any board from XES will probably consume too much power for our use.
    Most of the boards from XES have an approximate power draw of 20W and Marshall believes that we can find something closer to 7W.
*** We also added batteries to the contingency form
    Multistar High Capacity 100W*Hr, $90
*** Discussed using a micro controller
    Via USB to the main on board computer for use as a motor control.
*** Finally, we stressed the importance and desire to create redundant/backup systems
    As long as it isn't hurting the overall function and durability of the rover.
