* <2015-10-15>
** General Meeting Highlights
*** Main [[http://www.pioneerrobotics.weebly.com][Website]] started.
*** Looked at [[http://www.e-consystems.com][camera]].
*** General overview of the contingency request form.
    We are still looking and thinking of items that we want to add to the contingency form.
    We want as much money and as many items on it as possible, since we will only get a fraction of the money that we ask for.
** Software Meeting Highlights
*** The board from XES will probably consumes too much power
    Marshall explained that the board we were looking at from XES will probably not be ideal for our use because it consumes too much power.
    Marshall also explained that any board from XES will probably consume too much power for our use.
    Most of the boards from XES have an approximate power draw of 20W and Marshall believes that we can find something closer to 7W.
*** We also added batteries to the contingency form
    Multistar High Capacity 100W*Hr, $90
*** Discussed using a micro controller
    Via USB to the main on board computer for use as a motor control.
*** Finally, we stressed the importance and desire to create redundant/backup systems
    As long as it isn't hurting the overall function and durability of the rover.
